version: "3"
services:
    gateway:
        build:
            context: .
            dockerfile: /PhotoSi_IT_Demo_New.ApiGateway/Dockerfile
        ports:
            - "5000:80"
    ordini:
        build:
            context: .
            dockerfile: /PhotoSi_IT_Demo_New.Services.Ordini/Dockerfile
        ports:
            - "5001:80"
        depends_on:
            - db
    prodotti:
        build:
            context: .
            dockerfile: /PhotoSi_IT_Demo_New.Services.Prodotti/Dockerfile
        ports:
            - "5003:80"
        depends_on:
            - db
    utenti:
        build: 
            context: .
            dockerfile: /PhotoSi_IT_Demo_New.Services.Utenti/Dockerfile
        ports:
            - "5002:80"
        depends_on:
            - db
    recapiti:
        build: 
            context: .
            dockerfile: /PhotoSi_IT_Demo_New.Services.Recapiti/Dockerfile
        ports:
            - "5004:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"