// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoSi_IT_Demo_New.Services.Ordini.Data;

#nullable disable

namespace PhotoSi_IT_Demo_New.Services.Ordini.Migrations
{
    [DbContext(typeof(OrdiniDbContext))]
    [Migration("20220930171704_Aggiunto-RecapitoId")]
    partial class AggiuntoRecapitoId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PhotoSi_IT_Demo_New.Services.Ordini.Data.Entities.OrdineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AcquirenteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecapitoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ordini");
                });
#pragma warning restore 612, 618
        }
    }
}
